### ISSUE TITLE
Compatibility with Stretch

### ISSUE THREAD

**Issue by vertigoRod** [WatershedArts/Footfall#110]
Hi,
Did you guys have a chance to run it with RASPBIAN STRETCH?

**Comment by naraquev** [comment]
Yes! I was able to run it with Stretch

**Comment by c1audiu** [comment]
naraquev, can you help us with some info regarding the instalation on stretch? Like what version of openframeworks did you installed and other particularities. I olny managed to make it run on raspberrypi zero w with 2017-07-05-raspbian-jessie-lite and of_v0.9.8_linuxarmv6l_release.tar.gz. Thank you in advanced.

**Comment by black23** [comment]
@naraquev Please Can you say to us how to compile Footfall on Stretch?

**Comment by naraquev** [comment]
Hello all!
I was able to run it on Stretch with OP 0.10. There are several steps to do so. The CsvManager and HTTPManager needs several modifications. In my case I simply deleted the HTTPManager because I wanted to communicate with MQTT, with the CsvManager you have to check the using std and namespaces of the String types.

I hope this help you all!

**Comment by Ferni492** [comment]
@naraquev Please can you share the rpi3 image???

**Comment by DHaylock** [comment]
It is compatible with Raspbian Stretch you need to use openFrameworks 0.10. There are a number of caveats, You need to include the ofxPoco addon as without it ofxHttpUtils breaks. Everything else should work fine.

**Comment by mobileonekh** [comment]
OpenFrameworks is a main blocking point.

@DHaylock and @naraquev  Can you write more detail or give some link on how to get OpenFramework up and running on Stretch?

I try several approach but failed. Maybe because I am new to both Stretch and OF.

I use this link: https://forum.openframeworks.cc/t/compiling-of-in-raspbian-stretch/27562


Thanks
