### ISSUE TITLE
uncounted people stacking up

### ISSUE THREAD

**Issue by xeryuso** [WatershedArts/Footfall#40]
Hi i have managed to set up the system and it counts but i'm using it to know how many people are there in my apartment at any given time. I have counted every people at my apartment at the begining and started my database from 52. But there are some issues system doesn't count perfectly there are some people uncounted. This won't be a problem for a mall or a bussines place since you can reset the people in it at night when there is nobody at the building. But at an apartment you can't know the people in at any moment. I want to know if these errors will add up in time and affect the result.

If it affects the results how can i prevent it is there any suggestions ? I don't want to see some ridiculus numbers when i check my database 1 year later and i don't want to constantly count people manually once a month or something.

**Comment by oliverhumpage** [comment]
Hi,

Since computer vision isn’t 100% accurate, the counter will make mistakes. We found it accurate to about 7% (i.e. if it reports 100 people coming in, the true figure varies between 93-107).

Unfortunately we’ve found that it does tend to bias its mistakes in a particular direction, since lighting/shadows are the thing that most confuses it. Eg if a person walking in has a shadow ahead of them, sometimes the counter will think the shadow is a person going out. Similarly, the shadow of a person walking out can also be counted as a second person going out. This may be because we have our camera (and hence shadows) on the stairs - on flat ground results may be different.

If you pay extremely careful attention to placement, and experiment to see what position/lighting gives the best results, you can probably get it more accurate. It’ll never be perfect though - this software is meant to give a rough comparison of numbers and peak hours, not be accurate to the individual level.

All that said, we’re working on improving the image detection whenever we have a moment spare, so if you spot a new version do try it out.

Hope that explains things.

Oliver.
